import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { base32Encode, base32Decode } from '../src/lib/base32.js';
import { generateCode } from '../src/lib/totp.js';
import { decodeMigrationUri, encodeMigrationUris, extractUris } from '../src/lib/migration.js';
import { parseOtpauthUri, buildOtpauthUri, splitLabel } from '../src/lib/otpauth.js';

// A stand-in export, generated by scripts/make-fixture.mjs. It reproduces the
// label shapes a real Google Authenticator export contains -- empty issuer
// fields, bare service names, parenthesised labels, non-ASCII -- without
// anybody's real accounts in it.
const FIXTURE = new URL('./fixtures/example-export.txt', import.meta.url);

function importAll(text) {
  const { migration } = extractUris(text);
  return migration.flatMap((uri) => decodeMigrationUri(uri).accounts);
}

const fixtureAccounts = () => importAll(readFileSync(FIXTURE, 'utf8'));

test('base32 round-trips arbitrary bytes', () => {
  for (const len of [1, 5, 10, 15, 16, 20, 32, 40]) {
    const bytes = new Uint8Array(len).map((_, i) => (i * 37 + 11) & 0xff);
    assert.deepEqual(base32Decode(base32Encode(bytes)), bytes);
  }
});

test('base32 decoding is tolerant of formatting', () => {
  assert.deepEqual(base32Decode('jbsw y3dp'), base32Decode('JBSWY3DP'));
  assert.deepEqual(base32Decode('JBSW-Y3DP=='), base32Decode('JBSWY3DP'));
});

// RFC 6238 test vectors, secret "12345678901234567890".
test('TOTP matches RFC 6238 vectors', async () => {
  const secret = base32Encode(new TextEncoder().encode('12345678901234567890'));
  const cases = [
    [59, '287082'],
    [1111111109, '081804'],
    [1111111111, '050471'],
    [1234567890, '005924'],
    [2000000000, '279037'],
    [20000000000, '353130'],
  ];
  for (const [seconds, expected] of cases) {
    const code = await generateCode({ secret, digits: 6, period: 30, algorithm: 'SHA1', type: 'totp' }, seconds * 1000);
    assert.equal(code, expected, `t=${seconds}`);
  }
});

test('HOTP matches RFC 4226 vectors', async () => {
  const secret = base32Encode(new TextEncoder().encode('12345678901234567890'));
  const expected = ['755224', '287082', '359152', '969429', '338314', '254676', '287922', '162583', '399871', '520489'];
  for (let counter = 0; counter < expected.length; counter++) {
    const code = await generateCode({ secret, digits: 6, algorithm: 'SHA1', type: 'hotp', counter });
    assert.equal(code, expected[counter], `counter=${counter}`);
  }
});

test('decodes a multi-batch Google Authenticator export', () => {
  const accounts = fixtureAccounts();
  assert.equal(accounts.length, 25);
  assert.ok(accounts.every((a) => a.secret && a.type === 'totp' && a.digits === 6));

  const aws = accounts.find((a) => a.issuer === 'Amazon Web Services');
  assert.equal(aws.account, 'root-account-mfa-device@111122223333');

  // Issuer present only inside the "Issuer:account" label.
  const microsoft = accounts.find((a) => a.issuer === 'Microsoft');
  assert.equal(microsoft.account, 'exampleuser');

  // Bare "Namecheap (ExampleUser)" with no issuer field at all.
  const namecheap = accounts.find((a) => a.issuer === 'Namecheap');
  assert.equal(namecheap.account, 'ExampleUser');

  // A bare service name carries no account part.
  const ubisoft = accounts.find((a) => a.issuer === 'Ubisoft');
  assert.equal(ubisoft.account, '');

  // Issuer echoed inside the label gets trimmed off.
  const kraken = accounts.find((a) => a.issuer === 'kraken.com');
  assert.equal(kraken.account, 'Sign-in (ExampleUser)');

  // Non-ASCII survives the round trip.
  const uber = accounts.find((a) => a.issuer === 'Uber');
  assert.equal(uber.account, 'Renée Example');

  // Secret lengths vary in real exports; all of them must decode.
  const lengths = new Set(accounts.map((a) => base32Decode(a.secret).length));
  assert.ok(lengths.size >= 4, `varied secret lengths: ${[...lengths].join(', ')}`);
});

test('migration export round-trips back to identical secrets', () => {
  const original = fixtureAccounts();
  const uris = encodeMigrationUris(original, { perBatch: 10 });
  assert.equal(uris.length, 3);

  const decoded = uris.flatMap((uri) => decodeMigrationUri(uri).accounts);
  assert.equal(decoded.length, original.length);
  for (let i = 0; i < original.length; i++) {
    assert.equal(decoded[i].secret, original[i].secret, `secret ${i}`);
    assert.equal(decoded[i].issuer, original[i].issuer, `issuer ${i}`);
    assert.equal(decoded[i].account, original[i].account, `account ${i}`);
    assert.equal(decoded[i].digits, original[i].digits);
    assert.equal(decoded[i].algorithm, original[i].algorithm);
    assert.equal(decoded[i].type, original[i].type);
  }

  // Batch metadata should look like Google's own export.
  const meta = uris.map((u) => decodeMigrationUri(u));
  assert.deepEqual(meta.map((m) => m.batchIndex), [0, 1, 2]);
  assert.ok(meta.every((m) => m.batchSize === 3 && m.version === 1));
  assert.equal(new Set(meta.map((m) => m.batchId)).size, 1, 'batches share one id');
});

test('otpauth URIs round-trip', () => {
  for (const account of fixtureAccounts()) {
    const parsed = parseOtpauthUri(buildOtpauthUri(account));
    assert.equal(parsed.secret, account.secret);
    assert.equal(parsed.issuer, account.issuer);
    assert.equal(parsed.account, account.account);
  }
});

test('parses otpauth URIs from other apps', () => {
  const parsed = parseOtpauthUri('otpauth://totp/ACME%20Co:john@example.com?secret=JBSWY3DPEHPK3PXP&issuer=ACME%20Co&algorithm=SHA256&digits=8&period=60');
  assert.deepEqual(parsed, {
    type: 'totp',
    secret: 'JBSWY3DPEHPK3PXP',
    issuer: 'ACME Co',
    account: 'john@example.com',
    algorithm: 'SHA256',
    digits: 8,
    period: 60,
    counter: 0,
  });
});

test('rejects junk instead of importing it', () => {
  assert.throws(() => parseOtpauthUri('https://example.com'), /otpauth/);
  assert.throws(() => parseOtpauthUri('otpauth://totp/x?secret=!!!!'), /base32/);
  assert.throws(() => decodeMigrationUri('otpauth-migration://offline?nodata=1'), /data/);
});

test('splitLabel handles the shapes exporters actually produce', () => {
  assert.deepEqual(splitLabel('', 'GitHub:octocat'), { issuer: 'GitHub', account: 'octocat' });
  assert.deepEqual(splitLabel('Stripe', 'Stripe: a@b.com'), { issuer: 'Stripe', account: 'a@b.com' });
  assert.deepEqual(splitLabel('', 'Amazon'), { issuer: 'Amazon', account: '' });
  assert.deepEqual(splitLabel('', 'Namecheap (ExampleUser)'), { issuer: 'Namecheap', account: 'ExampleUser' });
  // An unrelated prefix must not be mistaken for the issuer.
  assert.deepEqual(splitLabel('Okta', 'corp:jane'), { issuer: 'Okta', account: 'corp:jane' });
});

// The fixture is generated by this project's own encoder, so on its own it only
// proves the codec agrees with itself. Point OTP_EXPORT_FILE at a genuine
// Google Authenticator export to check the decoder against real Google bytes.
// Skipped when no such file is present, so the suite stays portable.
const realExport = process.env.OTP_EXPORT_FILE
  || new URL('../otp_2fa_codes.txt', import.meta.url).pathname.replace(/^\//, '');

test('decodes a genuine Google Authenticator export', { skip: !existsSync(realExport) && 'no real export available' }, () => {
  const accounts = importAll(readFileSync(realExport, 'utf8'));
  assert.ok(accounts.length > 0, 'at least one account came out');
  for (const account of accounts) {
    assert.ok(account.secret, 'every entry has a secret');
    assert.ok(base32Decode(account.secret).length >= 10, 'secrets are of usable length');
    assert.ok(['totp', 'hotp'].includes(account.type));
    assert.ok(account.issuer || account.account, 'something to label it with');
  }
  // Re-encoding must preserve every secret exactly.
  const back = encodeMigrationUris(accounts).flatMap((uri) => decodeMigrationUri(uri).accounts);
  assert.deepEqual(back.map((a) => a.secret), accounts.map((a) => a.secret));
});
